In [10]:
import numpy as np
import math as mt
import turtle

In [15]:
turtle.shape("circle")
turtle.speed(1)

turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)

turtle.exitonclick()

In [ ]:
turtle.shape("turtle")
turtle.speed(1)
for i in range(4):
    turtle.forward(100)
    turtle.left(90)
turtle.exitonclick()

NameError: name 'turtle' is not defined

In [2]:
x=np.array([[3,5,7],[8,3,2]])
y=np.array([[4,5,1],[9,1,1]])
x.shape

(2, 3)

In [3]:
x[0,:2]

array([3, 5])

In [4]:
from numpy import int16


a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],dtype=int16)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int16)

In [5]:
print(np.square(a[1]))

[25 36 49 64]


In [6]:
a.ndim #define the diamentation

2

In [7]:
a.dtype

dtype('int16')

In [8]:
l=np.empty(4)
np.arange(5,9,1) #get random number from 5-<=9 dis -1

array([5, 6, 7, 8])

In [9]:
from ast import Try

def num1(c,d):
    try:
        x2 = (c, d)
        x3 = np.min(c, d)
        return x2, x3
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

(num1(5,3))

An error occurred: axis 3 is out of bounds for array of dimension 0
