In [ ]:
import numpy as np
import math as mt

In [3]:
x=np.array([[3,5,7],[8,3,2]])
y=np.array([[4,5,1],[9,1,1]])
x.shape

(2, 3)

In [4]:
x[0,:2]

array([3, 5])

In [18]:
from numpy import int16


a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],dtype=int16)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int16)

In [15]:
print(np.square(a[1]))

[25 36 49 64]


In [ ]:
a.ndim #define the diamentation

2

In [19]:
a.dtype

dtype('int16')

In [ ]:
l=np.empty(4)
np.arange(5,9,1) #get random number from 5-<=9 dis -1

array([5, 6, 7, 8])

In [ ]:
def num1(c,d):
    x2=(c,d)
    x3=np.min([c,d])
    return x2,x3

print(num1(5,3))

AxisError: axis 3 is out of bounds for array of dimension 0